global:
  secrets: {}
    #   # These secrets are shared between the various elastic components included with this helm chart.
    #   # These secrets are converted to all uppercase environment variables for metricbeat.
    #   # Secret 'secretName' can be used within the beat config as ${SECRETNAME}
    #   vSphereUsername: 
    #   vSpherePassword:
    #   cloudId:
    #   cloudAuth:
    #   # elasticHost:
    #   # elasticUser:
    #   # elasticPassword:
  proxyUrl: '' # i.e. http://squid.ip.domain.local:3128

metricbeat:
  enabled: false
  image: docker.elastic.co/beats/metricbeat:8.1.1
  restartPolicy: Always
  imagePullPolicy: Always
  vSphereHosts: [] # i.e. https://vcenter.hostname.or.ip/sdk
  config: |
    # This commented out example is useing a self-hosted elasticsearch cluster.
    # By default, elastic cloud is used with cloudId and cloudAuth.
    #output.elasticsearch:
    #  hosts: ["${ELASTICHOST}"]
    #  username: ${ELASTICUSER}
    #  password: ${ELASTICPASSWORD}
    #  ssl:
    #    enabled: true
    #    ca_trusted_fingerprint: "b9a10bbe64ee9826abeda6546fc988c8bf798b41957c33d05db736716513dc9c"
    cloud:
      id: ${CLOUDID}
      auth: ${CLOUDAUTH}
    {{- if .Values.global.proxyUrl }}
      proxy_url: {{ .Values.global.proxyUrl }}
    {{- end }}
    metricbeat.modules:
    - module: vsphere
      enabled: true
      metricsets: ["datastore", "host", "virtualmachine"]
      period: 10s
      hosts: 
    {{ toYaml .Values.metricbeat.vSphereHosts | indent 4 }}
      username: ${VSPHEREUSERNAME}
      password: ${VSPHEREPASSWORD}
      # If insecure is true, don't verify the server's certificate chain
      insecure: true
      # Get custom fields when using virtualmachine metric set. Default false.
      # get_custom_fields: false

filebeat:
  enabled: false
  image: docker.elastic.co/beats/filebeat:8.1.1
  restartPolicy: Always
  imagePullPolicy: Always
  # If elastic.filebeat.sharedIp is set to true, you cannot see the src address in the logs.
  # If the ip address is shared, the pod will only see communication from the IP address
  # of the node that it is running on.
  # If elastic.filebeat.sharedIp is set to false, externalTrafficPolicy will be set to Local.
  # See https://metallb.universe.tf/usage/ for more details.
  # If elastic.filebeat.sharedIp is set to false, you will need to set a unique IP address for
  # elastic.filebeat.loadBalancerIpAddress.
  # If you are listening on both TCP and UDP, you will require different IP addresses for each.
  sharedIp: true
  loadBalancerIpAddressUDP: ""
  loadBalancerIpAddressTCP: ""
  udpPorts:
    - "9002"
    - "9003"
  tcpPorts: []
  config: |
    # This commented out example is useing a self-hosted elasticsearch cluster.
    # By default, elastic cloud is used with cloudId and cloudAuth.
    #output.elasticsearch:
    #  hosts: ["${ELASTICHOST}"]
    #  username: ${ELASTICUSER}
    #  password: ${ELASTICPASSWORD}
    #  ssl:
    #    enabled: true
    #    ca_trusted_fingerprint: "b9a10bbe64ee9826abeda6546fc988c8bf798b41957c33d05db736716513dc9c"
    cloud:
      id: ${CLOUDID}
      auth: ${CLOUDAUTH}
    {{- if .Values.global.proxyUrl }}
      proxy_url: {{ .Values.global.proxyUrl }}
    {{- end }}
    filebeat.modules:
    - module: cisco
      ios:
        var.syslog_host: 0.0.0.0
        var.syslog_port: 9002
    filebeat.inputs:
    - type: syslog
      format: auto
      protocol.udp:
        host: "0.0.0.0:9003"
      processors:
        - drop_event:
            when:
              or:
                - equals:
                    syslog.severity_label: Debug
                - equals:
                    syslog.severity_label: Informational
                - equals:
                    syslog.severity_label: Notice
